### ISSUE TITLE
Possible Apache License violation

### ISSUE THREAD

**Issue by floragunn** [petaldevelopment/armor#11] opened 2015-12-10 22:07 UTC
Seems that this project derives from https://github.com/floragunncom/search-guard which is licensed under the Apache License 2. Pls. respect chapter 4 and make clear that your work derives from floragunncom searchguard as requested here: http://www.apache.org/licenses/LICENSE-2.0

Thanks!

**Comment by jmaitrehenry** [comment] 2015-12-10 22:26
Hi!

I will add this to the README of the project this week.

Thanks

**Comment by jmaitrehenry** [comment] 2015-12-11 02:09
I just push it into the 2.0 branch, I will merge it soon into master.
I add the notice into the licenses part of the README, is it correct for you @floragunncom ?

**Comment by jmaitrehenry** [comment] 2015-12-22 14:59
Without response, I close this issue. If you thinks it's not resolve, I will reopen it.

**Comment by floragunn** [comment] 2016-06-29 14:52
We still see no notice in master branch about the origin of this project and we also saw that you claimed the copyright to be "Copyright 2015 PetalMD", but neither you or PetalMD is the copyright owner of the code copied over from search guard 1. The copyright holder is floragunn. Please change the license and license headers accordingly.

Don't get us wrong, its no problem for us that you fork search guard (which is licensed under the ASL 2) but you have to respect this license and comply to it, especially if you act on behalf of a company (PetalMD).

You also have our public PGP key in your repository which makes really no sense and we ask kindly to remove this: https://github.com/petalmd/armor/blob/master/KEYS (and in all other branches too)

**Comment by jmaitrehenry** [comment] 2016-06-29 15:00
Hi @floragunncom,

The README was updated in another branch that just merge today: https://github.com/petalmd/armor/blob/master/README.md

This add the mention that this work is a derived works of yours.

I just create a PR for removing your KEY: https://github.com/petalmd/armor/pull/18
I will check for the licence header on top of files but a lot of them was modified since the initial fork.

If it's correct for you, I will merge it and consider this issue as close, if not, please respond here.

**Comment by jochenkressin** [comment] 2016-06-29 15:55
Hi @jmaitrehenry,

this is Jochen Kressin, CTO of floragunn. Since there seems to be some confusion about the license headers, I just like to clarify. First, we think it's a good thing that someone took over the 1.x codebase and continues to maintain it. We phased out support for 1.x, so we're happy you jumped in.

The issue we have with the fork are mainly the license headers. We're big supporters of OSS, but we also think that everyone should play by the same rules. I'm referring to section 4 of the Apache License, under which our code is distributed:

4b) "You must cause any modified files to carry prominent notices stating that You changed the files ... "
4c) "You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works"

and:

"You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or for any such Derivative Works as a whole, provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License."

So, this basically means that you cannot simply remove the copyright entry in the files and replace it by your own. If you made changes to the files, you may add your own copyright, but the original one (means, that of floragunn) has to stay intact. Please change the source files accordingly. If you have any additional questions, just drop me a PM.

Regards,

Jochen Kressin

**Comment by jmaitrehenry** [comment] 2016-07-09 01:40
As discuss by email, I reopen the issue.
The changes can be find here: https://github.com/petalmd/armor/pull/18

I will close this issue once the pull request will be merge.

**Comment by jmaitrehenry** [comment] 2016-08-05 19:24
As see in private, the issue is now fixed.

**Closed as completed by jmaitrehenry** 2016-08-05 19:24 UTC
